blank_issues_enabled: true
contact_links:
  - name: SunnahSleep App
    url: https://sunnahsleep.app
    about: Live app
  - name: Ummah.Build
    url: https://ummah.build
    about: Built by Ummah.Build
